x-common-variables: &common-variables
  POSTGRES_DB: assignment_1
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

services:
  db:
    image: postgres:17-alpine3.22
    environment:
      <<: *common-variables
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - course-assignment-1
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $POSTGRES_USER']
      interval: 10s
      timeout: 5s
      retries: 5
  core:
    build: .
    environment:
      <<: *common-variables
      POSTGRES_HOST: db
      PGPORT: 5432
      JWT_SECRET: secret
    depends_on:
      db:
        condition: service_healthy
    networks:
      - course-assignment-1
    deploy:
      replicas: 3
  nginx:
    image: nginx:alpine
    ports:
      - '3000:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - course-assignment-1
    depends_on:
      - core

networks:
  course-assignment-1:

volumes:
  db-data:
